sudo: required
services:
    -docker

before_install:
    - docker build -t chinlin9/react-test -f ./client/Dockerfile.dev ./client/

script:
    - docker run chinlin9/react-test npm test -- --coverage

after_success:
    - docker build -t chinlin9/multi-client ./client
    - docker build -t chinlin9/multi-nginx ./nginx
    - docker build -t chinlin9/multi-server ./server
    - docker build -t chinlin9/multi-worker ./worker
    #Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push chinlin9/multi-client
    - docker push chinlin9/multi-nginx
    - docker push chinlin9/multi-server
    - docker push chinlin9/multi-worker

deploy:
        provider: elasticbeanstalk
        region: us-east-2
        app: multi-docker
        env: MultiDocker-env
        bucket_name: elasticbeanstalk-us-east-2-938435876484
        bucket_path: docker-multi
        on:
            branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: 
            secure: $AWS_SECRET_KEY
        edge: true
        provider: elasticbeanstalk
