sudo: required
services:
    -docker

before_install:
    - docker build -t chinlin9/multi-docker -f ./client/Dockerfile.dev ./client/

script:
    - docker run chinlin9/multi-docker npm test -- --coverage

after_success:
    - docker build -t chinlin9/multi-docker ./client
    - docker build -t chinlin9/multi-docker ./clienginxnt
    - docker build -t chinlin9/multi-docker ./server
    - docker build -t chinlin9/multi-docker ./worker
    #Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push chinlin9/multi-docker
    - docker push chinlin9/multi-docker
    - docker push chinlin9/multi-docker
    - docker push chinlin9/multi-docker
